config/routes.rb
Rails.application.routes.draw do
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # ユーザー用
  # URL /users/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

    # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    resources :lifehacks, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
      #下書き一覧
      collection do
        get :index_draft
      end
      #コメント機能
      resources :lifehack_comments, only: [:create, :destroy]
      #いいね機能
      resource :favorites, only: [:create, :destroy]

    end
    resources :users, only: [:show, :update, :edit, :index] do
      collection do #id が付与されない
        get 'confirm'
        patch 'withdraw'
      end
      member do
        #ユーザーごとのいいね履歴一覧
        get :favorites
        #ユーザーごとの投稿履歴一覧
        get :index_user
      end
    end
    #通知機能
    resources :notifications, only: [:index] do
      post :update_checked, on: :collection
    end
    #キーワード検索機能
    get '/search', to: 'searches#search'
    #タグ検索機能
    get 'tagsearches/search', to: 'tagsearches#search'
  end

  namespace :admin do#URLの最初に/admin/が追加されます。
    root to: "homes#top"
    resources :users, only: [:index, :show, :edit, :update] do
      member do
        #ユーザーごとのいいね履歴一覧
        get :favorites
        #ユーザーごとの投稿履歴一覧
        get :index_user
      end
    end
    resources :lifehacks, only: [:show, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/lifehack.rb
class Lifehack < ApplicationRecord
  # いいね機能
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # コメント機能
  has_many :lifehack_comments, dependent: :destroy
  belongs_to :user

  # バリデーション

  # 下書き関連
  with_options presence: true, on: :publicize do
    validates :title
    validates :body
    validates :tag
  end

  validates :is_draft, inclusion: { in: [true, false] } # 下書き有無

  validates :title, presence: true, length: { minimum: 2, maximum: 20 } # タイトル最小2文字、最大20文字
  validates :body, presence: true, length: { minimum: 10, maximum: 200 } # 本文最小10文字、最大200文字
  validates :tag, length: { minimum: 2, maximum: 20 } # タグ設定最小2文字、最大20文字

  # 検索機能、条件分岐
  def self.search_for(content, method)
    if method == 'perfect'
      Lifehack.where(title: content)
    elsif method == 'forward'
      Lifehack.where('title LIKE ?', content + '%')
    elsif method == 'backward'
      Lifehack.where('title LIKE ?', '%' + content)
    else
      Lifehack.where('title LIKE ?', '%' + content + '%')
    end
  end

  # 通知機能
  has_many :notifications, dependent: :destroy
  # lifehackへのいいね通知機能
  def create_notification_favorite_lifehack!(current_user)
    # 同じユーザーが同じ投稿に既にいいねしていないかを確認
    existing_notification = Notification.find_by(lifehack_id: id, visitor_id: current_user.id, action: 'favorite_lifehack')

    # すでにいいねされていない場合のみ通知レコードを作成
    return unless existing_notification.nil? && current_user != user

    notification = Notification.new(
      lifehack_id: id,
      visitor_id: current_user.id,
      visited_id: user.id,
      action: 'favorite_lifehack'
    )

    return unless notification.valid?

    notification.save
  end

  unless method_defined?(:create_notification_comment!)
    def create_notification_comment!(current_user, comment_id)
      existing_notification = Notification.find_by(lifehack_id: id, visitor_id: current_user.id, action: 'comment')

      return unless existing_notification.nil? && current_user != user

      notification = Notification.new(
        lifehack_id: id,
        visitor_id: current_user.id,
        visited_id: user.id,
        action: 'comment'
      )

      # カラムが存在する場合のみセットする
      notification.comment_id = comment_id if Notification.column_names.include?('comment_id')

      notification.save if notification.valid?
    end
  end

  has_many_attached :lifehack_images # 画像投稿関連

  FILE_NUMBER_LIMIT = 3

  validate :validate_number_of_files

  def validate_number_of_files
    return if lifehack_images.length <= FILE_NUMBER_LIMIT

    errors.add(:画像解説, "に添付できる画像は#{FILE_NUMBER_LIMIT}枚までです。")
  end
end

app/controllers/admin/lifehacks_controller.rb
class Admin::LifehacksController < ApplicationController
  def show
    @lifehack = Lifehack.find(params[:id])
    @lifehack_comments = @lifehack.lifehack_comments.order(created_at: :desc)
  end

  def destroy
    @lifehack = Lifehack.find(params[:id])
    @lifehack.destroy
    redirect_to admin_root_path, notice: '管理者権限により投稿を削除しました。'
  end
end

app/helpers/admin/lifehacks_helper.rb
module Admin::LifehacksHelper
end

app/views/admin/lifehacks/_index.html.erb
<% lifehacks.each do |lifehack| %>
  <div class="list-group">
    <div class="list-group-item list-group-item-action lifehack_list" aria-current="true">
      <div class="d-flex w-100 justify-content-between">
        <h4 class="mb-1">
          <%= image_tag 'miniature light bulb.png', size: "50x50" %>
          <%= link_to lifehack.title, admin_lifehack_path(lifehack), class: "text-reset lifehack-title" %><!--タイトル-->
        </h4>
        <small>
            投稿日<%= lifehack.created_at.strftime('%Y/%m/%d') %><!--投稿日-->
            （更新日<%= lifehack.updated_at.strftime('%Y/%m/%d') %>）<!--更新日-->
        </small>
      </div>
        <p class="mb-1">
          <%= link_to lifehack.body.truncate(60), admin_lifehack_path(lifehack), class: "text-reset" %><!--本文-->
        </p>
        <div class="d-flex w-100 justify-content-between">
        <p class="mx-3 mt-4">
          タグ<i class="fa-solid fa-tags"></i>[
            <%= link_to lifehack.tag, tagsearches_search_path(tagcontent: lifehack.tag) %><!--タグ-->
          ]
        </p>
          <div class="d-flex justify-content-end">
            <div class="mx-3 mt-4">
              <div class="icon-container">
                <i class="fas fa-heart" aria-hidden="true"></i>
                <%= lifehack.favorites.count %><!--いいね-->
              </div>
          </div>
          <div class="mx-3 mt-4">
            <%= render "public/lifehacks/static.rate", lifehack: lifehack %><!--おすすめ度-->
          </div>
          <div class="mx-3 mt-4">
            <%= render "public/lifehack_comments/counter", lifehack: lifehack %><!--コメント数-->
          </div>
        </div>
      </div>
      <small>
        （投稿者）
          <%= link_to admin_user_path(lifehack.user) do %>
            <%= image_tag lifehack.user.get_profile_image(50, 50) %><!--投稿者詳細-->
            <%= lifehack.user.account_name %>
          <% end %>
      </small>
    </div>
  </div>
<% end %>

app/views/admin/lifehacks/show.html.erb
<div class="container py-1">
  <h3 class="mt-3">
    <i class="fa-regular fa-file"></i>
    投稿詳細
  </h3>
  <div class="card">
    <div class="lifehack_images justify-content-center mt-2">
      <% if @lifehack.lifehack_images.attached? %><!--画像追加がされたとき-->
        <% @lifehack.lifehack_images.each do |image| %>
          <a href="<%= rails_blob_path(image, only_path: true) %>" data-lightbox="group" data-title="投稿画像"><!--lightbox2(投稿画像拡大表示)-->
            <%= image_tag image.variant(resize: "330x330") %>
          </a>
        <% end %>
      <% else %><!--画像追加がされなかったとき-->
        <%= image_tag 'no_lifehack_image.jpg' %>
      <% end %>
    </div>
    <div class="card-body">
      <div class="d-flex justify-content-between">
        <h4 class="card-title col-7">
          <%= image_tag 'miniature light bulb.png', size: "50x50" %>
          <span class="lifehack-title"><%= @lifehack.title %></span>
        </h4>
        <p class="col-5 text-center">
          <small>
            投稿日<%= @lifehack.created_at.strftime('%Y/%m/%d') %><!--投稿日-->
            （更新日<%= @lifehack.updated_at.strftime('%Y/%m/%d') %>）<!--更新日-->
          </small>
        </p>
      </div>
      <div class="col-12">
        <p class="card-text">
          <%= simple_format(@lifehack.body) %>
        </p>
      </div>
    </div>

    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <div class="d-flex justify-content-between">
          <h4 class="card-title col-3 text-center">
            おすすめ度
          </h4>
          <div class="col-9 text-center">
            <%= render "public/lifehacks/static.rate", lifehack: @lifehack %>
          </div>
        </div>
      </li>
      <li class="list-group-item">
        <div class="d-flex justify-content-between">
          <h4 class="card-title col-3 text-center">
            タグ
          </h4>
          <div class="col-9 text-center">
            <%= link_to @lifehack.tag, tagsearches_search_path(tagcontent: @lifehack.tag) %>
          </div>
        </div>
      </li>

      <li class="list-group-item">
        <div class="d-flex justify-content-between">
          <h4 class="card-title col-3 text-center">
            投稿者
          </h4>
          <div class="col-9 text-center">
            <%= link_to admin_user_path(@lifehack.user) do %>
              <%= image_tag @lifehack.user.get_profile_image(50, 50) %><!--投稿者詳細-->
              <%= @lifehack.user.account_name %>
            <% end %>
          </div>
        </div>
      </li>

      <li class="list-group-item">
        <div class="d-flex justify-content-between">
          <h4 class="card-title col-3 text-center">
            いいね数
          </h4>
          <div class="col-9 text-center">
            <i class="fas fa-heart" aria-hidden="true"></i>
            <%= @lifehack.favorites.count %>
          </div>
        </div>
      </li>
      <li class="list-group-item">
        <div class="d-flex justify-content-between">
          <h4 class="card-title col-3 text-center">
            コメント件数
          </h4>
            <div class="lifehack-comments-counter col-9 text-center"><!--create.js.erbとdestroy.js.erbでクラスの指定とアクションを記述してるので変更不可!-->
              <%= render "public/lifehack_comments/counter", lifehack: @lifehack %><!--コメント数-->
            </div>
        </div>
      </li>
      <li class="list-group-item">
        <div class="d-flex">
          <h4 class="card-title col-3 text-center">
            コメント一覧
          </h4>
            <div class="lifehack-comments-index col-9 text-center"><!--create.js.erbとdestroy.js.erbでクラスの指定とアクションを記述してるので変更不可!-->
            <%= render "public/lifehack_comments/index", lifehack_comments: @lifehack_comments %><!--コメント一覧、削除-->
          </div>
        </div>
      </li>
    </ul>
  <div class="row">
    <div class="col-12 text-center mt-5">
      <%= link_to '管理者権限により投稿を削除する', admin_lifehack_path(@lifehack), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-danger destroy_lifehack_#{@lifehack.id} mb-4"  %>
    </div>
  </div>
</div>