config/routes.rb
Rails.application.routes.draw do
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # ユーザー用
  # URL /users/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

    # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    resources :lifehacks, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
      #下書き一覧
      collection do
        get :index_draft
      end
      #コメント機能
      resources :lifehack_comments, only: [:create, :destroy]
      #いいね機能
      resource :favorites, only: [:create, :destroy]

    end
    resources :users, only: [:show, :update, :edit, :index] do
      collection do #id が付与されない
        get 'confirm'
        patch 'withdraw'
      end
      member do
        #ユーザーごとのいいね履歴一覧
        get :favorites
        #ユーザーごとの投稿履歴一覧
        get :index_user
      end
    end
    #通知機能
    resources :notifications, only: [:index] do
      post :update_checked, on: :collection
    end
    #キーワード検索機能
    get '/search', to: 'searches#search'
    #タグ検索機能
    get 'tagsearches/search', to: 'tagsearches#search'
  end

  namespace :admin do#URLの最初に/admin/が追加されます。
    root to: "homes#top"
    resources :users, only: [:index, :show, :edit, :update] do
      member do
        #ユーザーごとのいいね履歴一覧
        get :favorites
        #ユーザーごとの投稿履歴一覧
        get :index_user
      end
    end
    resources :lifehacks, only: [:show, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && !is_active
  end

  has_many :lifehacks, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :lifehack_comments, dependent: :destroy

  validates :account_name, presence: true, length: { minimum: 2, maximum: 20 } # アカウント名最小2文字、最大20文字
  validates :introduction, length: { maximum: 50 } # 紹介文最大50文字

  has_one_attached :profile_image

  # ゲストユーザーを作成するメソッド
  def self.guest
    find_or_create_by!(email: 'guest@example.com', account_name: 'ゲストアカウント') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end

  # 検索機能、条件分岐
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(account_name: content)
    elsif method == 'forward'
      User.where('account_name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('account_name LIKE ?', '%' + content)
    else
      User.where('account_name LIKE ?', '%' + content + '%')
    end
  end

  # プロフィール画像を取得するメソッド
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_user_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # 通知機能
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).per(10)
                 .order(created_at: :desc)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = '会員情報を更新しました'
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  def favorites
    @user = User.find(params[:id])
    favorite_ids = Favorite.where(user_id: @user.id)
                           .order(created_at: :desc) # いいねの日時で降順にソート
                           .pluck(:lifehack_id)
    @favorite_lifehacks = Lifehack.where(id: favorite_ids)
                                  .page(params[:page]).per(10)
                                  .order(created_at: :desc)
                                  .where(is_draft: false)
  end

  def index_user
    @user = User.find(params[:id])
    @lifehacks = Lifehack.where(user_id: params[:id])
                         .page(params[:page]).per(10)
                         .order(created_at: :desc)
                         .where(is_draft: false)
  end

  private

  def user_params
    params.require(:user).permit(:is_active)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_index.html.erb
<% users.each do |user| %>
  <div class="list-group">
    <%= link_to admin_user_path(user.id) do %>
      <div class="list-group-item list-group-item-action d-flex user_list">
        <%= image_tag user.get_profile_image(100, 100), class: "mr-3" %>
        <div class="d-flex justify-content-between flex-grow-1">
          <div class=" text-center mx-auto mt-5">
            ユーザー名<br>
            <%= user.account_name %>
          </div>
          <div class=" text-center mx-auto mt-5">
            ステータス
            <% if user.is_active == true %>
              <p class="text-secondary">退会</p>
            <% else %>
              <p class="text-success">有効</p>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="container py-1">
  <div class="row">
    <div class="col-12 text-start">
      <h3 class="mt-3 mb-5">
        <i class="fa-solid fa-users-gear"></i>
        ユーザー情報編集
      </h3>
      <%= form_with model: @user, url: admin_user_path(@user), method: :patch do |f| %>
        <%= render 'layouts/error', obj: @user %>
        <div class="table-responsive"> <!-- レスポンシブ対応のためにtable-responsiveを追加 -->
          <table class="table table-hover table-borderless">
            <tr>
              <td class="user_item">
                アカウント名
              </td>
              <td class="user_detail">
                <%= @user.account_name %>
              </td>
            </tr>
            <tr>
              <td class="user_item">
                プロフィール画像
              </td>
              <td><%= image_tag @user.get_profile_image(200, 200) %></td>
            </tr>
            <tr>
              <td class="user_item">
                紹介文
              </td>
              <td class="user_detail">
                <% if @user.introduction.present? %>
                  <%= @user.introduction %>
                <% else %>
                  紹介文が設定されるとここに表示されます.
                <% end %>
              </td>
            </tr>
            <tr>
              <td class="user_item">
                会員ステータス
              </td>
              <td class="user_detail">
                <%= f.radio_button :is_active, true %>
                <%= f.label :is_active_true, "退会" %>
                <%= f.radio_button :is_active, false %>
                <%= f.label :is_active_false, "有効" %>
              </td>
            </tr>
          </table>
        </div>
        <div class="row">
          <div class="col-12">
            <div class="text-center">
              <%= f.submit "変更内容を保存", class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/favorites.html.erb
<div class="container py-1">
  <div class="row">
    <div class="col-12 text-start">
      <h3 class="mt-3">
        <i class="fas fa-heart" aria-hidden="true"></i>
          <%= "#{@user.account_name}のいいねした投稿一覧" %>
      </h3>
    </div>
  </div>
  <div class="row">
    <div class="custom heart col-12 text-start">
      <%= render "admin/lifehacks/index", lifehacks: @favorite_lifehacks %>
    </div>
  </div>
    <%= render "layouts/page", obj: @favorite_lifehacks %>
</div>

app/views/admin/users/index.html.erb
<div class="container py-1">
  <div class="row">
    <div class="col-12 text-start">
      <h3 class="mt-3">
        <i class="fa-solid fa-users"></i>
          ユーザー一覧
      </h3>
    </div>
  </div>
  <div class="row">
    <div class="col-12 text-start">
      <%= render 'index', users: @users %>
    </div>
  </div>
    <%= render "layouts/page", obj: @users %>
</div>

app/views/admin/users/index_user.html.erb
<div class="container py-1">
  <div class="row">
    <div class="col-12 text-start">
      <h3 class="mt-3">
        <i class="fa-solid fa-list"></i>
          <%= "#{@user.account_name}の投稿履歴一覧" %>
      </h3>
    </div>
  </div>
  <div class="row">
    <div class="col-12 text-start">
      <%= render "admin/lifehacks/index", lifehacks: @lifehacks %>
    </div>
  </div>
    <%= render "layouts/page", obj: @lifehacks %>
</div>

app/views/admin/users/show.html.erb
<div class="container py-1">
  <div class="row">
    <div class="col-12 text-start">
      <h3 class="mt-3 mb-5">
        <i class="fa-regular fa-user"></i>
        ユーザーページ
      </h3>
      <div class="d-flex mb-3">
        <h4><b>登録情報</b></h4>
        <%= link_to "編集する", edit_admin_user_path(@user.id), class:"btn btn-success ml-3" %>
      </div>
    </div>
  </div>
  <div class="card mb-3">
    <div class="row g-0">
      <div class="profile_image col-md-4 my-3">
        <%= image_tag @user.get_profile_image(300, 300), width: 300, height: 300 %>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h4 class="card-title">
            <%= @user.account_name %>
          </h4>
          <h5 class="mt-5">
            紹介文
          </h5>
          <p class="card-text">
            <% if @user.introduction.present? %>
              <%= @user.introduction %>
            <% else %>
              紹介文が設定されるとここに表示されます。
            <% end %>
          </p>
          <h6 class="card-text d-flex w-100 mt-5">
            <p class="mr-3">
              会員ステータス
            </p>
            <% if @user.is_active == true %>
              <p class="text-secondary">退会</p>
            <% else %>
              <p class="text-success">有効</p>
            <% end %>
          </h6>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="d-flex flex-wrap align-center">
        <h4><b>投稿履歴</b></h4>
        <%= link_to "一覧を見る", index_user_admin_user_path(@user), class: "btn btn-outline-primary ml-2 mr-4 mb-4" %>
        <h4><b>いいね一覧</b></h4>
        <%= link_to "一覧を見る", favorites_admin_user_path(@user), class: "btn btn-outline-success ml-2 mb-4" %>
      </div>
    </div>
  </div>
</div>