config/routes.rb
Rails.application.routes.draw do
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # ユーザー用
  # URL /users/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

    # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    resources :lifehacks, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
      #下書き一覧
      collection do
        get :index_draft
      end
      #コメント機能
      resources :lifehack_comments, only: [:create, :destroy]
      #いいね機能
      resource :favorites, only: [:create, :destroy]

    end
    resources :users, only: [:show, :update, :edit, :index] do
      collection do #id が付与されない
        get 'confirm'
        patch 'withdraw'
      end
      member do
        #ユーザーごとのいいね履歴一覧
        get :favorites
        #ユーザーごとの投稿履歴一覧
        get :index_user
      end
    end
    #通知機能
    resources :notifications, only: [:index] do
      post :update_checked, on: :collection
    end
    #キーワード検索機能
    get '/search', to: 'searches#search'
    #タグ検索機能
    get 'tagsearches/search', to: 'tagsearches#search'
  end

  namespace :admin do#URLの最初に/admin/が追加されます。
    root to: "homes#top"
    resources :users, only: [:index, :show, :edit, :update] do
      member do
        #ユーザーごとのいいね履歴一覧
        get :favorites
        #ユーザーごとの投稿履歴一覧
        get :index_user
      end
    end
    resources :lifehacks, only: [:show, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
  <h2><%= obj.errors.count %>件のエラーにより保存できませんでした。</h2>
  <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="mt-auto footer">
  <div class="container-fluid py-4">
    <div class="row">
      <div class="footer_text_area mx-auto">
        <a href="https://github.com/hidakashun/small_lifehack">
          <i class="fab fa-github"></i>
          Github link: created by hidakashun
        </a>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <nav class="navbar navbar-expand-sm navbar-light">
    <div class="container">
      <div class="d-flex">
        <!-- ロゴ -->
        <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag 'icon.png', size: "150x100" %>
        <% end %>

        <!-- ハンバーガーメニュー -->
        <div class="button">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>

      <div class="welcome_user col-sm-3 text-center">
        <% if user_signed_in? %>
          <p>ようこそ、</p>
          <p><%= "#{current_user.account_name}さん！" %></p>
        <% end %>
      </div>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item d-flex">
              <%= link_to user_path(current_user), class: "nav-link" do %>
                <i class="fas fa-user"></i> マイページ
              <% end %>
            </li>
            <li class="nav-item d-flex">
              <%= link_to new_lifehack_path, class: "nav-link" do %>
                <i class="fa-regular fa-pen-to-square"></i> 新規投稿
              <% end %>
            </li>
            <li class="nav-item d-flex">
              <%= link_to lifehacks_path, class: "nav-link" do %>
                <i class="fa-solid fa-list"></i> 投稿一覧
              <% end %>
            </li>
            <li class="nav-item d-flex">
              <%= link_to users_path, class: "nav-link" do %>
                <i class="fa-solid fa-users"></i> ユーザー一覧
              <% end %>
            </li>
            <li class="nav-item d-flex">
              <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
                <i class="fa-solid fa-right-from-bracket"></i> ログアウト
              <% end %>
            </li>
          <% elsif admin_signed_in? %>
            <li class="nav-item d-flex">
              <%= link_to admin_root_path, class: "nav-link" do %>
                <i class="fa-solid fa-list"></i> 投稿一覧
              <% end %>
            </li>
            <li class="nav-item d-flex">
              <%= link_to admin_users_path, class: "nav-link" do %>
                <i class="fa-solid fa-users"></i> ユーザー一覧
              <% end %>
            </li>
            <li class="nav-item d-flex">
              <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link" do %>
                <i class="fa-solid fa-right-from-bracket"></i> ログアウト
              <% end %>
            </li>
          <% else %>
            <li class="nav-item d-flex">
              <%= link_to about_path, class: "nav-link" do %>
                <i class="fa-solid fa-house"></i> About
              <% end %>
            </li>
            <li class="nav-item d-flex">
              <%= link_to lifehacks_path, class: "nav-link" do %>
                <i class="fa-solid fa-list"></i> 投稿一覧
              <% end %>
            </li>
            <li class="nav-item d-flex">
              <%= link_to users_path, class: "nav-link" do %>
                <i class="fa-solid fa-users"></i> ユーザー一覧
              <% end %>
            </li>
            <li class="nav-item d-flex">
              <%= link_to new_user_registration_path, class: "nav-link" do %>
                <i class="fa-regular fa-handshake"></i> 新規登録
              <% end %>
            </li>
            <li class="nav-item d-flex">
              <%= link_to new_user_session_path, class: "nav-link" do %>
                <i class="fa-solid fa-right-to-bracket"></i> ログイン
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div>
      <% unless user_signed_in? || admin_signed_in? %>
        <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: "guest_btn btn" %>
      <% end %>
      <!--通知機能-->
      <% if user_signed_in? %>
        <div class="mypage-nav d-flex align-items-center">
          <div class="bell-container mr-3">
            <a href="javascript:void(0)" id="notifications-link">
              <% if unchecked_notifications.any? %>
                <span class="fa-stack" style="vertical-align: middle;">
                  <i class="far fa-bell fa-lg fa-stack-1x" style="font-size: 1.5em;"></i>
                  <i class="fas fa-circle n-circle fa-stack-1x">
                    <span class="notification-count"><%= unchecked_notifications.count %></span>
                  </i>
                </span>
              <% else %>
                <i class="far fa-bell fa-lg" style="font-size: 1.5em;"></i>
              <% end %>
            </a>
          </div>
        </div>
        <div id="notifications-modal" class="modal">
          <div class="common-modal-content"></div>
        </div>
      <% end %>
      <!--通知機能-->
    </div>
  </nav>
  <div class="row d-flex justify-content-between py-2 mx-auto">
    <div class="col-sm-8">
      <%= render 'public/searches/form' %><!--キーワード検索機能-->
    </div>
    <div class="col-sm-4">
      <%= render 'public/tagsearches/form' %><!--タグ検索機能-->
    </div>
  </div>
</header>


<script>//通知機能のモーダル
  $(document).ready(function() {
    $('#notifications-link').click(function() {
      // 通知を確認済みに更新するアクションを呼び出す
      $.ajax({
        url: '<%= update_checked_notifications_path %>',
        type: 'POST',
        headers: {//CSRF（Cross-Site Request Forgery）対策のためにトークン
          'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
        },
        success: function() {
          $('.n-circle').removeClass('orange');
          $('#notifications-link').html('<i class="far fa-bell fa-lg" style="font-size: 1.5em;"></i>');

          // 通知モーダルを表示する処理
          $.ajax({
            url: '<%= notifications_path(@user) %>',
            type: 'GET',
            success: function(response) {
              $('#notifications-modal .common-modal-content').html(response);
              $('#notifications-modal').addClass('fade-in').show();
            }
          });
        }
      });
    });

  // モーダル内のクリックイベントを停止
  $('#notifications-modal .modal-content').on('click', function(event) {
    event.stopPropagation(); // イベントの伝播を停止
  });

  // モーダル外（背景）をクリックしたときにモーダルを閉じる
  $('#notifications-modal').on('click', function() {
    $(this).addClass('fade-out');
    setTimeout(() => {
      $(this).hide().removeClass('fade-out');
    }, 300);
  });
});
</script>

app/views/layouts/_page.html.erb
<div class="row justify-content-center mt-3 mb-4">
  <%= paginate obj %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'favicon.icon' %><!--サイトのタグのアイコン設定-->
    <title>Small Lifehack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/><!--スライドショー-->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/><!--スライドショー-->
    <script src="https://kit.fontawesome.com/cdce8a28a2.js" crossorigin="anonymous"></script>
    <%# ↓ここから %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+2:wght@500&display=swap" rel="stylesheet">
    <%# ↑ここまでGoogle Font導入 %>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet"><!--lightbox2(投稿画像拡大表示)-->

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column h-100" style="color: #495057; background-color: #FFFFFF; font-family: 'M PLUS 2', sans-serif;">
    <%# ↑の行のfont-familyでフォント名を指定 %>
    <%= render 'layouts/header' %>
    <main>
      <div class="container flex-shrink-0">
        <%= flash[:notice] %>
        <%= flash[:alert] %>
      <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <script>
      $(function(){
      //スライドショー
        $('.slider').slick({
        //スライドの矢印を非表示にする
        arrows: false,
        //ドットを表示させる
        dots: true,
        //スライドショーの自動再生(カーソルが画像の上に乗るとスライドショーが止まる)
        autoplay: true,
        //自動再生のスピード(1000→1秒、3000→3秒)
        autoplaySpeed: 5000,
        });
      });
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script><!--lightbox2(投稿画像拡大表示)-->
  </body>
</html>